"""
The ORBINOVASTRO(tm) Score Legend and Assessment Layers, exactly as they
appear on the reference report (page 7 of the client's own sample PDF).
This is fixed, client-independent reference material -- it is never
generated by the AI and never changes per report, so it is hardcoded here
rather than re-derived every run.

Circle counts/colors for every numeric L/LT/TT figure are computed
DETERMINISTICALLY from the number itself via score_bracket() -- never left
to the AI to guess -- so a cell can never show a green circle next to a
negative number or any other internally-inconsistent combination.

The AI is still responsible for the *qualitative* "Assessment" verdict
each house/planet/area gets (a holistic judgment across L, LT and TT
together, e.g. a house with a very negative L but a very positive TT might
be labelled "Rebuilding" rather than simply averaging the three numbers).
To keep that verdict internally consistent with its own circle/color, the
AI is asked to choose one of the fixed TIER keys below (never invent its
own), and Python renders the circles from that tier -- so the word and the
color can never disagree.
"""

from __future__ import annotations

# ---------------------------------------------------------------------
# Score Legend (Table on page 7): numeric score -> circle count + color
# ---------------------------------------------------------------------
SCORE_LEGEND_ROWS = [
    # (low, high, circle_count, color, meaning, interpretation)
    (10, None, 3, "green", "Exceptional", "Outstanding support or activation"),
    (6, 9, 2, "green", "Very Strong", "Highly favorable"),
    (1, 5, 1, "green", "Positive", "Supportive"),
    (0, 0, 1, "yellow", "Neutral", "Depends on effort and other chart factors"),
    (-4, -1, 1, "red", "Challenging", "Obstacles, sensitivity or delays"),
    (-8, -5, 2, "red", "High Risk", "Significant challenges"),
    (None, -9, 3, "red", "Critical", "Immediate strategic attention required"),
]


def score_bracket(score: float) -> tuple[int, str, str]:
    """Returns (circle_count, color_name, meaning_word) for a numeric L/LT/TT
    score, using the exact brackets from the Score Legend table."""
    n = round(score)
    if n >= 10:
        return (3, "green", "Exceptional")
    if 6 <= n <= 9:
        return (2, "green", "Very Strong")
    if 1 <= n <= 5:
        return (1, "green", "Positive")
    if n == 0:
        return (1, "yellow", "Neutral")
    if -4 <= n <= -1:
        return (1, "red", "Challenging")
    if -8 <= n <= -5:
        return (2, "red", "High Risk")
    return (3, "red", "Critical")


# ---------------------------------------------------------------------
# Assessment tiers -- the fixed vocabulary the AI must choose from for
# every holistic "Assessment" verdict (houses, planets, strategic focus
# areas, scorecard, conclusion). circle_count/color mirror the Score
# Legend exactly so a tier's color is never inconsistent with its meaning.
# ---------------------------------------------------------------------
TIER_CIRCLES = {
    "exceptional": (3, "green"),
    "very_strong": (2, "green"),
    "positive": (1, "green"),
    "neutral": (1, "yellow"),
    "challenging": (1, "red"),
    "high_risk": (2, "red"),
    "critical": (3, "red"),
}

TIER_KEYS = list(TIER_CIRCLES.keys())

# ---------------------------------------------------------------------
# Assessment Layers (Table on page 7): L / LT / TT definitions.
# ---------------------------------------------------------------------
ASSESSMENT_LAYERS_ROWS = [
    ("L", "Natal—Life Potential", "Lifelong strengths, vulnerabilities and karmic blueprint"),
    ("LT", "Transit → Natal", "How current planetary movements activate the natal chart"),
    ("TT", "Transit Environment", "Interaction among current planetary positions and the prevailing environment"),
]

# ---------------------------------------------------------------------
# Acronym Legend (2026-09-08 addition, client request: "write the legend
# of acronyms there are many"). Every abbreviation used anywhere else in
# the report -- the L/LT/TT layer codes (already explained in more detail
# in ASSESSMENT_LAYERS_ROWS above, repeated here for a single one-stop
# glossary), the report/table-name acronyms, and the ten planet codes used
# throughout Table 2 -- gathered into one place. Static, client-independent
# reference material, same as the tables above: never AI-generated, never
# changes per report.
# ---------------------------------------------------------------------
ACRONYM_LEGEND_ROWS = [
    ("LBI", "Life Balance Index — this report's overall framework"),
    ("CCSI", "Cusp Conflict Stress Indicator — the underlying numeric score every L/LT/TT figure comes from"),
    ("PII", "Planetary Influence Assessment — Table 2's per-planet scoring"),
    ("L", "Natal / Life Potential (Lagna Chart)"),
    ("LT", "Transit-to-Natal Activation"),
    ("TT", "Transit-to-Transit (current Transit Environment)"),
    ("Asc", "Ascendant"),
    ("Su", "Sun"),
    ("Mo", "Moon"),
    ("Ma", "Mars"),
    ("Me", "Mercury"),
    ("Ju", "Jupiter"),
    ("Ve", "Venus"),
    ("Sa", "Saturn"),
    ("Ra", "Rahu"),
    ("Ke", "Ketu"),
]

# ---------------------------------------------------------------------
# Fixed category lists for Table 3 (Strategic Focus Areas) and Table 4
# (Scorecard) -- kept as a stable, reusable template across every client's
# report (matching "my file has better organization" -- the same
# structure every time, only the tier/label/text content changes per
# client) rather than left for the AI to invent fresh each run.
# ---------------------------------------------------------------------
STRATEGIC_FOCUS_AREAS = [
    "Wealth & Monetization",
    "Service & Employment",
    "Partnerships & Clients",
    "Transformation & Research",
    "Remote / Foreign Opportunities",
    "Career & Formal Status",
    "Communication & Outreach",
    "Creativity & Speculation",
    "Networking & Gains",
    "Health & Routine",
    "Emotional Balance",
    "Spiritual Development",
]

SCORECARD_CATEGORIES = [
    "Overall Life Balance",
    "Natal Potential",
    "Current Activation",
    "Current Cosmic Environment",
    "Financial Opportunity",
    "Service & Client Opportunity",
    "Transformation & Research",
    "Career Momentum",
    "Communication",
    "Creativity & Speculative Judgment",
    "Networking & Gains",
    "Emotional Balance",
    "Remote / Foreign Potential",
    "Spiritual Development",
]

CONCLUSION_ROWS = [
    "Overall Chart Strength",
    "Primary Strengths",
    "Highest Opportunities",
    "Priority Areas",
    "Current Life Theme",
    "Long-Term Direction",
]
